Redis - pipelined deprecation fixes
bia-technologies/lowkiq pull request #32
Opened 2023-04-07 17:24 UTC by ruban-thilak

Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

```ruby
redis.multi do
  redis.get("key")
end
```

should be replaced by

```ruby
redis.multi do |pipeline|
  pipeline.get("key")
end
```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

```ruby
redis.pipelined do
  redis.get("key")
end
```

should be replaced by

```ruby
redis.pipelined do |pipeline|
  pipeline.get("key")
end
```

2023-04-11 13:19 UTC, darkleaf commented
@ruban-thilak Thank you for your contribution, but I cannot accept it now.
First, we have planned to add CI. I hope this task will be done soon.
Second, please split this PR into two parts and add more info and links.

2023-04-12 05:26 UTC, ruban-thilak commented
Sure @darkleaf, I will split this PR. 
If adding CI is the priority, I can set up Rubocop & test in GitHub actions.

2023-04-18 07:29 UTC, darkleaf commented on lib/lowkiq/queue/actions.rb
> +          redis.multi do |pipeline|
@ruban-thilak please check this point carefully again

2023-04-18 07:44 UTC, darkleaf requested changes
.

2023-07-03 07:42 UTC, closed without merging